// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inc.proto

package inc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 代理映射
type Mapping struct {
	InternalIp           string   `protobuf:"bytes,1,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	InternalPort         int32    `protobuf:"varint,2,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	ExternalPort         int32    `protobuf:"varint,3,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	MapId                uint32   `protobuf:"varint,5,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SlaveId              uint32   `protobuf:"varint,6,opt,name=slave_id,json=slaveId,proto3" json:"slave_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Mapping) Reset()         { *m = Mapping{} }
func (m *Mapping) String() string { return proto.CompactTextString(m) }
func (*Mapping) ProtoMessage()    {}
func (*Mapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{0}
}

func (m *Mapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mapping.Unmarshal(m, b)
}
func (m *Mapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mapping.Marshal(b, m, deterministic)
}
func (m *Mapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mapping.Merge(m, src)
}
func (m *Mapping) XXX_Size() int {
	return xxx_messageInfo_Mapping.Size(m)
}
func (m *Mapping) XXX_DiscardUnknown() {
	xxx_messageInfo_Mapping.DiscardUnknown(m)
}

var xxx_messageInfo_Mapping proto.InternalMessageInfo

func (m *Mapping) GetInternalIp() string {
	if m != nil {
		return m.InternalIp
	}
	return ""
}

func (m *Mapping) GetInternalPort() int32 {
	if m != nil {
		return m.InternalPort
	}
	return 0
}

func (m *Mapping) GetExternalPort() int32 {
	if m != nil {
		return m.ExternalPort
	}
	return 0
}

func (m *Mapping) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Mapping) GetMapId() uint32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *Mapping) GetSlaveId() uint32 {
	if m != nil {
		return m.SlaveId
	}
	return 0
}

// 注册代理映射
type RegisterReq struct {
	InternalIp           string   `protobuf:"bytes,1,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	InternalPort         int32    `protobuf:"varint,2,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	ExternalPort         int32    `protobuf:"varint,3,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{1}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetInternalIp() string {
	if m != nil {
		return m.InternalIp
	}
	return ""
}

func (m *RegisterReq) GetInternalPort() int32 {
	if m != nil {
		return m.InternalPort
	}
	return 0
}

func (m *RegisterReq) GetExternalPort() int32 {
	if m != nil {
		return m.ExternalPort
	}
	return 0
}

func (m *RegisterReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// 注销代理映射
type UnregisterReq struct {
	ExternalPort         uint32   `protobuf:"varint,1,opt,name=external_port,json=externalPort,proto3" json:"external_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnregisterReq) Reset()         { *m = UnregisterReq{} }
func (m *UnregisterReq) String() string { return proto.CompactTextString(m) }
func (*UnregisterReq) ProtoMessage()    {}
func (*UnregisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{2}
}

func (m *UnregisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnregisterReq.Unmarshal(m, b)
}
func (m *UnregisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnregisterReq.Marshal(b, m, deterministic)
}
func (m *UnregisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnregisterReq.Merge(m, src)
}
func (m *UnregisterReq) XXX_Size() int {
	return xxx_messageInfo_UnregisterReq.Size(m)
}
func (m *UnregisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UnregisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_UnregisterReq proto.InternalMessageInfo

func (m *UnregisterReq) GetExternalPort() uint32 {
	if m != nil {
		return m.ExternalPort
	}
	return 0
}

type DialReq struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DialReq) Reset()         { *m = DialReq{} }
func (m *DialReq) String() string { return proto.CompactTextString(m) }
func (*DialReq) ProtoMessage()    {}
func (*DialReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{3}
}

func (m *DialReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DialReq.Unmarshal(m, b)
}
func (m *DialReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DialReq.Marshal(b, m, deterministic)
}
func (m *DialReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DialReq.Merge(m, src)
}
func (m *DialReq) XXX_Size() int {
	return xxx_messageInfo_DialReq.Size(m)
}
func (m *DialReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DialReq.DiscardUnknown(m)
}

var xxx_messageInfo_DialReq proto.InternalMessageInfo

func (m *DialReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{4}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AuthReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthReq) Reset()         { *m = AuthReq{} }
func (m *AuthReq) String() string { return proto.CompactTextString(m) }
func (*AuthReq) ProtoMessage()    {}
func (*AuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{5}
}

func (m *AuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthReq.Unmarshal(m, b)
}
func (m *AuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthReq.Marshal(b, m, deterministic)
}
func (m *AuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthReq.Merge(m, src)
}
func (m *AuthReq) XXX_Size() int {
	return xxx_messageInfo_AuthReq.Size(m)
}
func (m *AuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthReq proto.InternalMessageInfo

func (m *AuthReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type RpcResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RpcResp) Reset()         { *m = RpcResp{} }
func (m *RpcResp) String() string { return proto.CompactTextString(m) }
func (*RpcResp) ProtoMessage()    {}
func (*RpcResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{6}
}

func (m *RpcResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RpcResp.Unmarshal(m, b)
}
func (m *RpcResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RpcResp.Marshal(b, m, deterministic)
}
func (m *RpcResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RpcResp.Merge(m, src)
}
func (m *RpcResp) XXX_Size() int {
	return xxx_messageInfo_RpcResp.Size(m)
}
func (m *RpcResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RpcResp.DiscardUnknown(m)
}

var xxx_messageInfo_RpcResp proto.InternalMessageInfo

func (m *RpcResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type StreamData struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamData) Reset()         { *m = StreamData{} }
func (m *StreamData) String() string { return proto.CompactTextString(m) }
func (*StreamData) ProtoMessage()    {}
func (*StreamData) Descriptor() ([]byte, []int) {
	return fileDescriptor_a9ee4de5949f8e83, []int{7}
}

func (m *StreamData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamData.Unmarshal(m, b)
}
func (m *StreamData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamData.Marshal(b, m, deterministic)
}
func (m *StreamData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamData.Merge(m, src)
}
func (m *StreamData) XXX_Size() int {
	return xxx_messageInfo_StreamData.Size(m)
}
func (m *StreamData) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamData.DiscardUnknown(m)
}

var xxx_messageInfo_StreamData proto.InternalMessageInfo

func (m *StreamData) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Mapping)(nil), "mapping")
	proto.RegisterType((*RegisterReq)(nil), "register_req")
	proto.RegisterType((*UnregisterReq)(nil), "unregister_req")
	proto.RegisterType((*DialReq)(nil), "dial_req")
	proto.RegisterType((*LoginReq)(nil), "login_req")
	proto.RegisterType((*AuthReq)(nil), "auth_req")
	proto.RegisterType((*RpcResp)(nil), "rpc_resp")
	proto.RegisterType((*StreamData)(nil), "stream_data")
}

func init() { proto.RegisterFile("inc.proto", fileDescriptor_a9ee4de5949f8e83) }

var fileDescriptor_a9ee4de5949f8e83 = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x65, 0xda, 0xb4, 0xe9, 0xb4, 0x45, 0x28, 0x02, 0x29, 0x48, 0x48, 0x0d, 0x86, 0x45,
	0x57, 0x6c, 0x10, 0x17, 0x60, 0x97, 0x1d, 0xca, 0x92, 0x4d, 0x64, 0x62, 0x2b, 0x58, 0xc4, 0x3f,
	0x8c, 0x5d, 0xc4, 0x5d, 0xb8, 0x10, 0xc7, 0x42, 0x99, 0x26, 0xa8, 0x15, 0x17, 0x60, 0xe5, 0x99,
	0xf7, 0x3e, 0xcf, 0xf8, 0x49, 0x86, 0x85, 0xb6, 0xcd, 0x9d, 0x47, 0x17, 0x1d, 0xff, 0x66, 0x30,
	0x37, 0xc2, 0x7b, 0x6d, 0xdb, 0x6c, 0x03, 0x4b, 0x6d, 0xa3, 0x42, 0x2b, 0xba, 0x5a, 0xfb, 0x9c,
	0x15, 0x6c, 0xbb, 0xa8, 0x60, 0x94, 0x4a, 0x9f, 0xdd, 0xc0, 0xfa, 0x17, 0xf0, 0x0e, 0x63, 0x7e,
	0x52, 0xb0, 0x6d, 0x52, 0xad, 0x46, 0xf1, 0xc9, 0x61, 0xec, 0x21, 0xf5, 0x79, 0x08, 0x4d, 0xf6,
	0xd0, 0x28, 0x12, 0x54, 0xc0, 0x52, 0xaa, 0xd0, 0xa0, 0xf6, 0x51, 0x3b, 0x9b, 0x4f, 0x69, 0xd5,
	0xa1, 0x94, 0x5d, 0xc0, 0xcc, 0x08, 0x5f, 0x6b, 0x99, 0x27, 0x05, 0xdb, 0xae, 0xab, 0xc4, 0x08,
	0x5f, 0xca, 0xec, 0x12, 0xd2, 0xd0, 0x89, 0x0f, 0xd5, 0x1b, 0x33, 0x32, 0xe6, 0xd4, 0x97, 0x92,
	0x7f, 0x31, 0x58, 0xa1, 0x6a, 0x75, 0x88, 0x0a, 0x6b, 0x54, 0xef, 0xff, 0x2a, 0x0f, 0x7f, 0x80,
	0xd3, 0x9d, 0x3d, 0x7a, 0xde, 0x9f, 0xc1, 0x8c, 0xf2, 0x1c, 0x0d, 0xe6, 0xb7, 0x90, 0x4a, 0x2d,
	0x3a, 0xba, 0x90, 0xc3, 0x5c, 0x48, 0x89, 0x2a, 0x84, 0x21, 0xcb, 0xd8, 0xf2, 0x0d, 0x2c, 0x3a,
	0xd7, 0x6a, 0x4b, 0x58, 0x06, 0x53, 0x2b, 0x8c, 0x1a, 0x18, 0xaa, 0x79, 0x01, 0xa9, 0xd8, 0xc5,
	0x57, 0xf2, 0xcf, 0x21, 0x89, 0xee, 0x4d, 0xd9, 0x01, 0xd8, 0x37, 0xfc, 0x0a, 0x52, 0xf4, 0x4d,
	0x8d, 0x2a, 0xf8, 0xec, 0x0c, 0x26, 0x26, 0xb4, 0x83, 0xdf, 0x97, 0xfc, 0x1a, 0x96, 0x21, 0xa2,
	0x12, 0xa6, 0x96, 0x22, 0x8a, 0x7e, 0x45, 0x7f, 0x12, 0xb1, 0xaa, 0xa8, 0x7e, 0x4c, 0x9e, 0x27,
	0xda, 0x36, 0x2f, 0x33, 0xfa, 0x57, 0xf7, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x83, 0x92, 0x26,
	0x1c, 0x64, 0x02, 0x00, 0x00,
}
