// Code generated by protoc-gen-go. DO NOT EDIT.
// source: intun.proto

package net

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 内网服务器注册到中心服务器
type LeafRegisterReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeafRegisterReq) Reset()         { *m = LeafRegisterReq{} }
func (m *LeafRegisterReq) String() string { return proto.CompactTextString(m) }
func (*LeafRegisterReq) ProtoMessage()    {}
func (*LeafRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{0}
}

func (m *LeafRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeafRegisterReq.Unmarshal(m, b)
}
func (m *LeafRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeafRegisterReq.Marshal(b, m, deterministic)
}
func (m *LeafRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafRegisterReq.Merge(m, src)
}
func (m *LeafRegisterReq) XXX_Size() int {
	return xxx_messageInfo_LeafRegisterReq.Size(m)
}
func (m *LeafRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_LeafRegisterReq proto.InternalMessageInfo

func (m *LeafRegisterReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LeafRegisterResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	ID                   uint32   `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeafRegisterResp) Reset()         { *m = LeafRegisterResp{} }
func (m *LeafRegisterResp) String() string { return proto.CompactTextString(m) }
func (*LeafRegisterResp) ProtoMessage()    {}
func (*LeafRegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{1}
}

func (m *LeafRegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeafRegisterResp.Unmarshal(m, b)
}
func (m *LeafRegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeafRegisterResp.Marshal(b, m, deterministic)
}
func (m *LeafRegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeafRegisterResp.Merge(m, src)
}
func (m *LeafRegisterResp) XXX_Size() int {
	return xxx_messageInfo_LeafRegisterResp.Size(m)
}
func (m *LeafRegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LeafRegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_LeafRegisterResp proto.InternalMessageInfo

func (m *LeafRegisterResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LeafRegisterResp) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

// 控制台连接内网服务器
type CliAuthReq struct {
	Password             string   `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliAuthReq) Reset()         { *m = CliAuthReq{} }
func (m *CliAuthReq) String() string { return proto.CompactTextString(m) }
func (*CliAuthReq) ProtoMessage()    {}
func (*CliAuthReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{2}
}

func (m *CliAuthReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliAuthReq.Unmarshal(m, b)
}
func (m *CliAuthReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliAuthReq.Marshal(b, m, deterministic)
}
func (m *CliAuthReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliAuthReq.Merge(m, src)
}
func (m *CliAuthReq) XXX_Size() int {
	return xxx_messageInfo_CliAuthReq.Size(m)
}
func (m *CliAuthReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CliAuthReq.DiscardUnknown(m)
}

var xxx_messageInfo_CliAuthReq proto.InternalMessageInfo

func (m *CliAuthReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CliAuthResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	ID                   uint32   `protobuf:"varint,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliAuthResp) Reset()         { *m = CliAuthResp{} }
func (m *CliAuthResp) String() string { return proto.CompactTextString(m) }
func (*CliAuthResp) ProtoMessage()    {}
func (*CliAuthResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{3}
}

func (m *CliAuthResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliAuthResp.Unmarshal(m, b)
}
func (m *CliAuthResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliAuthResp.Marshal(b, m, deterministic)
}
func (m *CliAuthResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliAuthResp.Merge(m, src)
}
func (m *CliAuthResp) XXX_Size() int {
	return xxx_messageInfo_CliAuthResp.Size(m)
}
func (m *CliAuthResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CliAuthResp.DiscardUnknown(m)
}

var xxx_messageInfo_CliAuthResp proto.InternalMessageInfo

func (m *CliAuthResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CliAuthResp) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

// 控制台命令到中心服务器
type CliCommandReq struct {
	Cmd                  string   `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliCommandReq) Reset()         { *m = CliCommandReq{} }
func (m *CliCommandReq) String() string { return proto.CompactTextString(m) }
func (*CliCommandReq) ProtoMessage()    {}
func (*CliCommandReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{4}
}

func (m *CliCommandReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliCommandReq.Unmarshal(m, b)
}
func (m *CliCommandReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliCommandReq.Marshal(b, m, deterministic)
}
func (m *CliCommandReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliCommandReq.Merge(m, src)
}
func (m *CliCommandReq) XXX_Size() int {
	return xxx_messageInfo_CliCommandReq.Size(m)
}
func (m *CliCommandReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CliCommandReq.DiscardUnknown(m)
}

var xxx_messageInfo_CliCommandReq proto.InternalMessageInfo

func (m *CliCommandReq) GetCmd() string {
	if m != nil {
		return m.Cmd
	}
	return ""
}

type CliCommandResp struct {
	Ret                  string   `protobuf:"bytes,2,opt,name=ret,proto3" json:"ret,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CliCommandResp) Reset()         { *m = CliCommandResp{} }
func (m *CliCommandResp) String() string { return proto.CompactTextString(m) }
func (*CliCommandResp) ProtoMessage()    {}
func (*CliCommandResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{5}
}

func (m *CliCommandResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CliCommandResp.Unmarshal(m, b)
}
func (m *CliCommandResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CliCommandResp.Marshal(b, m, deterministic)
}
func (m *CliCommandResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CliCommandResp.Merge(m, src)
}
func (m *CliCommandResp) XXX_Size() int {
	return xxx_messageInfo_CliCommandResp.Size(m)
}
func (m *CliCommandResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CliCommandResp.DiscardUnknown(m)
}

var xxx_messageInfo_CliCommandResp proto.InternalMessageInfo

func (m *CliCommandResp) GetRet() string {
	if m != nil {
		return m.Ret
	}
	return ""
}

// 心跳
type Heartbeat struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Heartbeat) Reset()         { *m = Heartbeat{} }
func (m *Heartbeat) String() string { return proto.CompactTextString(m) }
func (*Heartbeat) ProtoMessage()    {}
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{6}
}

func (m *Heartbeat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Heartbeat.Unmarshal(m, b)
}
func (m *Heartbeat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Heartbeat.Marshal(b, m, deterministic)
}
func (m *Heartbeat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Heartbeat.Merge(m, src)
}
func (m *Heartbeat) XXX_Size() int {
	return xxx_messageInfo_Heartbeat.Size(m)
}
func (m *Heartbeat) XXX_DiscardUnknown() {
	xxx_messageInfo_Heartbeat.DiscardUnknown(m)
}

var xxx_messageInfo_Heartbeat proto.InternalMessageInfo

// 创建隧道
type CreateTunnelReq struct {
	LeafID               uint32   `protobuf:"varint,1,opt,name=leafID,proto3" json:"leafID,omitempty"`
	Address              string   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTunnelReq) Reset()         { *m = CreateTunnelReq{} }
func (m *CreateTunnelReq) String() string { return proto.CompactTextString(m) }
func (*CreateTunnelReq) ProtoMessage()    {}
func (*CreateTunnelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{7}
}

func (m *CreateTunnelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTunnelReq.Unmarshal(m, b)
}
func (m *CreateTunnelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTunnelReq.Marshal(b, m, deterministic)
}
func (m *CreateTunnelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTunnelReq.Merge(m, src)
}
func (m *CreateTunnelReq) XXX_Size() int {
	return xxx_messageInfo_CreateTunnelReq.Size(m)
}
func (m *CreateTunnelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTunnelReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTunnelReq proto.InternalMessageInfo

func (m *CreateTunnelReq) GetLeafID() uint32 {
	if m != nil {
		return m.LeafID
	}
	return 0
}

func (m *CreateTunnelReq) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type CreateTunnelResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	TunnelID             string   `protobuf:"bytes,2,opt,name=tunnelID,proto3" json:"tunnelID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTunnelResp) Reset()         { *m = CreateTunnelResp{} }
func (m *CreateTunnelResp) String() string { return proto.CompactTextString(m) }
func (*CreateTunnelResp) ProtoMessage()    {}
func (*CreateTunnelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{8}
}

func (m *CreateTunnelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTunnelResp.Unmarshal(m, b)
}
func (m *CreateTunnelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTunnelResp.Marshal(b, m, deterministic)
}
func (m *CreateTunnelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTunnelResp.Merge(m, src)
}
func (m *CreateTunnelResp) XXX_Size() int {
	return xxx_messageInfo_CreateTunnelResp.Size(m)
}
func (m *CreateTunnelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTunnelResp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTunnelResp proto.InternalMessageInfo

func (m *CreateTunnelResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateTunnelResp) GetTunnelID() string {
	if m != nil {
		return m.TunnelID
	}
	return ""
}

// 创建隧道
type CloseTunnelReq struct {
	LeafID               uint32   `protobuf:"varint,1,opt,name=leafID,proto3" json:"leafID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseTunnelReq) Reset()         { *m = CloseTunnelReq{} }
func (m *CloseTunnelReq) String() string { return proto.CompactTextString(m) }
func (*CloseTunnelReq) ProtoMessage()    {}
func (*CloseTunnelReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{9}
}

func (m *CloseTunnelReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseTunnelReq.Unmarshal(m, b)
}
func (m *CloseTunnelReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseTunnelReq.Marshal(b, m, deterministic)
}
func (m *CloseTunnelReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseTunnelReq.Merge(m, src)
}
func (m *CloseTunnelReq) XXX_Size() int {
	return xxx_messageInfo_CloseTunnelReq.Size(m)
}
func (m *CloseTunnelReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseTunnelReq.DiscardUnknown(m)
}

var xxx_messageInfo_CloseTunnelReq proto.InternalMessageInfo

func (m *CloseTunnelReq) GetLeafID() uint32 {
	if m != nil {
		return m.LeafID
	}
	return 0
}

type CloseTunnelResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseTunnelResp) Reset()         { *m = CloseTunnelResp{} }
func (m *CloseTunnelResp) String() string { return proto.CompactTextString(m) }
func (*CloseTunnelResp) ProtoMessage()    {}
func (*CloseTunnelResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{10}
}

func (m *CloseTunnelResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseTunnelResp.Unmarshal(m, b)
}
func (m *CloseTunnelResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseTunnelResp.Marshal(b, m, deterministic)
}
func (m *CloseTunnelResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseTunnelResp.Merge(m, src)
}
func (m *CloseTunnelResp) XXX_Size() int {
	return xxx_messageInfo_CloseTunnelResp.Size(m)
}
func (m *CloseTunnelResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseTunnelResp.DiscardUnknown(m)
}

var xxx_messageInfo_CloseTunnelResp proto.InternalMessageInfo

func (m *CloseTunnelResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 隧道消息
type TunnelMessageReq struct {
	Close                bool     `protobuf:"varint,1,opt,name=close,proto3" json:"close,omitempty"`
	TunID                string   `protobuf:"bytes,3,opt,name=tunID,proto3" json:"tunID,omitempty"`
	Data                 []byte   `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelMessageReq) Reset()         { *m = TunnelMessageReq{} }
func (m *TunnelMessageReq) String() string { return proto.CompactTextString(m) }
func (*TunnelMessageReq) ProtoMessage()    {}
func (*TunnelMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{11}
}

func (m *TunnelMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelMessageReq.Unmarshal(m, b)
}
func (m *TunnelMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelMessageReq.Marshal(b, m, deterministic)
}
func (m *TunnelMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelMessageReq.Merge(m, src)
}
func (m *TunnelMessageReq) XXX_Size() int {
	return xxx_messageInfo_TunnelMessageReq.Size(m)
}
func (m *TunnelMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelMessageReq proto.InternalMessageInfo

func (m *TunnelMessageReq) GetClose() bool {
	if m != nil {
		return m.Close
	}
	return false
}

func (m *TunnelMessageReq) GetTunID() string {
	if m != nil {
		return m.TunID
	}
	return ""
}

func (m *TunnelMessageReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type TunnelMessageResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TunnelMessageResp) Reset()         { *m = TunnelMessageResp{} }
func (m *TunnelMessageResp) String() string { return proto.CompactTextString(m) }
func (*TunnelMessageResp) ProtoMessage()    {}
func (*TunnelMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_76f4cf0dc0f704f9, []int{12}
}

func (m *TunnelMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TunnelMessageResp.Unmarshal(m, b)
}
func (m *TunnelMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TunnelMessageResp.Marshal(b, m, deterministic)
}
func (m *TunnelMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TunnelMessageResp.Merge(m, src)
}
func (m *TunnelMessageResp) XXX_Size() int {
	return xxx_messageInfo_TunnelMessageResp.Size(m)
}
func (m *TunnelMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_TunnelMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_TunnelMessageResp proto.InternalMessageInfo

func (m *TunnelMessageResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*LeafRegisterReq)(nil), "leaf_register_req")
	proto.RegisterType((*LeafRegisterResp)(nil), "leaf_register_resp")
	proto.RegisterType((*CliAuthReq)(nil), "cli_auth_req")
	proto.RegisterType((*CliAuthResp)(nil), "cli_auth_resp")
	proto.RegisterType((*CliCommandReq)(nil), "cli_command_req")
	proto.RegisterType((*CliCommandResp)(nil), "cli_command_resp")
	proto.RegisterType((*Heartbeat)(nil), "heartbeat")
	proto.RegisterType((*CreateTunnelReq)(nil), "create_tunnel_req")
	proto.RegisterType((*CreateTunnelResp)(nil), "create_tunnel_resp")
	proto.RegisterType((*CloseTunnelReq)(nil), "close_tunnel_req")
	proto.RegisterType((*CloseTunnelResp)(nil), "close_tunnel_resp")
	proto.RegisterType((*TunnelMessageReq)(nil), "tunnel_message_req")
	proto.RegisterType((*TunnelMessageResp)(nil), "tunnel_message_resp")
}

func init() { proto.RegisterFile("intun.proto", fileDescriptor_76f4cf0dc0f704f9) }

var fileDescriptor_76f4cf0dc0f704f9 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6b, 0xfa, 0x30,
	0x14, 0xc7, 0xa9, 0x55, 0x7f, 0xf6, 0xa9, 0xbf, 0x69, 0x36, 0x46, 0xf1, 0x24, 0xd9, 0x86, 0xe2,
	0x61, 0x30, 0x06, 0xfb, 0x03, 0xa4, 0x3b, 0xf4, 0x1a, 0x76, 0xda, 0xa5, 0xc4, 0xf6, 0x4d, 0x05,
	0x9b, 0xba, 0x24, 0x65, 0xff, 0xfe, 0xc8, 0x6b, 0x94, 0xcd, 0x79, 0xf0, 0xf6, 0xfd, 0x96, 0xcf,
	0xfb, 0xbc, 0xa4, 0x04, 0xfa, 0x5b, 0x65, 0x6b, 0xf5, 0xb8, 0xd7, 0x95, 0xad, 0xf8, 0x0c, 0xc6,
	0x3b, 0x94, 0x1f, 0x99, 0xc6, 0xf5, 0xd6, 0x58, 0xd4, 0x99, 0xc6, 0x4f, 0xc6, 0xa0, 0xad, 0x64,
	0x89, 0x71, 0x30, 0x0d, 0xe6, 0x91, 0xa0, 0xcc, 0x5f, 0x80, 0x9d, 0x82, 0x66, 0xcf, 0x46, 0x10,
	0x96, 0x66, 0xed, 0x41, 0x17, 0xd9, 0x7f, 0x68, 0xa5, 0x49, 0xdc, 0x9a, 0x06, 0xf3, 0xa1, 0x68,
	0xa5, 0x09, 0x5f, 0xc0, 0x20, 0xdf, 0x6d, 0x33, 0x59, 0xdb, 0x0d, 0xb9, 0x27, 0xd0, 0xdb, 0x4b,
	0x63, 0xbe, 0x2a, 0x5d, 0xf8, 0xb1, 0x63, 0xe7, 0x4f, 0x30, 0xfc, 0xc1, 0x5e, 0xa4, 0xbf, 0x83,
	0x2b, 0x37, 0x92, 0x57, 0x65, 0x29, 0x55, 0x41, 0x1b, 0x46, 0x10, 0xe6, 0xe5, 0x41, 0xee, 0x22,
	0xbf, 0x87, 0xd1, 0x6f, 0xa8, 0x51, 0x6b, 0xb4, 0x64, 0x8a, 0x84, 0x8b, 0xbc, 0x0f, 0xd1, 0x06,
	0xa5, 0xb6, 0x2b, 0x94, 0x96, 0xbf, 0xc2, 0x38, 0xd7, 0x28, 0x2d, 0x66, 0xb6, 0x56, 0x0a, 0x77,
	0x64, 0xbe, 0x85, 0xae, 0xfb, 0x07, 0x69, 0x42, 0xf2, 0xa1, 0xf0, 0x8d, 0xc5, 0xf0, 0x4f, 0x16,
	0x85, 0x46, 0x63, 0xbc, 0xef, 0x50, 0xf9, 0x12, 0xd8, 0xa9, 0xe6, 0xec, 0xb5, 0x26, 0xd0, 0x6b,
	0x00, 0x7f, 0xb9, 0x48, 0x1c, 0x3b, 0x5f, 0xb8, 0xd3, 0x57, 0xe6, 0x92, 0x93, 0xf0, 0x07, 0x18,
	0x9f, 0xb0, 0xe7, 0xd6, 0xf1, 0x37, 0x60, 0x1e, 0x28, 0xd1, 0x18, 0xb9, 0x46, 0x92, 0xde, 0x40,
	0x87, 0x86, 0x89, 0xec, 0x89, 0xa6, 0xb8, 0xaf, 0xb6, 0x56, 0x69, 0x12, 0x87, 0x34, 0xdf, 0x14,
	0xf7, 0x44, 0x0a, 0x69, 0x65, 0xdc, 0x9e, 0x06, 0xf3, 0x81, 0xa0, 0xcc, 0x67, 0x70, 0xfd, 0xc7,
	0x7a, 0x6e, 0xfd, 0xb2, 0xf3, 0x1e, 0x2a, 0xb4, 0xab, 0x2e, 0x3d, 0xc1, 0xe7, 0xef, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xc8, 0x3f, 0x80, 0x73, 0x91, 0x02, 0x00, 0x00,
}
