// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proxy.proto

package net

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 端口映射
type ProxyMapping struct {
	LocalPort            int32    `protobuf:"varint,1,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	RemotePort           int32    `protobuf:"varint,2,opt,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyMapping) Reset()         { *m = ProxyMapping{} }
func (m *ProxyMapping) String() string { return proto.CompactTextString(m) }
func (*ProxyMapping) ProtoMessage()    {}
func (*ProxyMapping) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{0}
}

func (m *ProxyMapping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyMapping.Unmarshal(m, b)
}
func (m *ProxyMapping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyMapping.Marshal(b, m, deterministic)
}
func (m *ProxyMapping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyMapping.Merge(m, src)
}
func (m *ProxyMapping) XXX_Size() int {
	return xxx_messageInfo_ProxyMapping.Size(m)
}
func (m *ProxyMapping) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyMapping.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyMapping proto.InternalMessageInfo

func (m *ProxyMapping) GetLocalPort() int32 {
	if m != nil {
		return m.LocalPort
	}
	return 0
}

func (m *ProxyMapping) GetRemotePort() int32 {
	if m != nil {
		return m.RemotePort
	}
	return 0
}

func (m *ProxyMapping) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

// 注册
type ProxyRegisterReq struct {
	Maps                 []*ProxyMapping `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProxyRegisterReq) Reset()         { *m = ProxyRegisterReq{} }
func (m *ProxyRegisterReq) String() string { return proto.CompactTextString(m) }
func (*ProxyRegisterReq) ProtoMessage()    {}
func (*ProxyRegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{1}
}

func (m *ProxyRegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyRegisterReq.Unmarshal(m, b)
}
func (m *ProxyRegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyRegisterReq.Marshal(b, m, deterministic)
}
func (m *ProxyRegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyRegisterReq.Merge(m, src)
}
func (m *ProxyRegisterReq) XXX_Size() int {
	return xxx_messageInfo_ProxyRegisterReq.Size(m)
}
func (m *ProxyRegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyRegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyRegisterReq proto.InternalMessageInfo

func (m *ProxyRegisterReq) GetMaps() []*ProxyMapping {
	if m != nil {
		return m.Maps
	}
	return nil
}

type ProxyRegisterResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyRegisterResp) Reset()         { *m = ProxyRegisterResp{} }
func (m *ProxyRegisterResp) String() string { return proto.CompactTextString(m) }
func (*ProxyRegisterResp) ProtoMessage()    {}
func (*ProxyRegisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{2}
}

func (m *ProxyRegisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyRegisterResp.Unmarshal(m, b)
}
func (m *ProxyRegisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyRegisterResp.Marshal(b, m, deterministic)
}
func (m *ProxyRegisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyRegisterResp.Merge(m, src)
}
func (m *ProxyRegisterResp) XXX_Size() int {
	return xxx_messageInfo_ProxyRegisterResp.Size(m)
}
func (m *ProxyRegisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyRegisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyRegisterResp proto.InternalMessageInfo

func (m *ProxyRegisterResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 取消
type ProxyUnregisterReq struct {
	RemotePort           []int32  `protobuf:"varint,1,rep,packed,name=remote_port,json=remotePort,proto3" json:"remote_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyUnregisterReq) Reset()         { *m = ProxyUnregisterReq{} }
func (m *ProxyUnregisterReq) String() string { return proto.CompactTextString(m) }
func (*ProxyUnregisterReq) ProtoMessage()    {}
func (*ProxyUnregisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{3}
}

func (m *ProxyUnregisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyUnregisterReq.Unmarshal(m, b)
}
func (m *ProxyUnregisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyUnregisterReq.Marshal(b, m, deterministic)
}
func (m *ProxyUnregisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyUnregisterReq.Merge(m, src)
}
func (m *ProxyUnregisterReq) XXX_Size() int {
	return xxx_messageInfo_ProxyUnregisterReq.Size(m)
}
func (m *ProxyUnregisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyUnregisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyUnregisterReq proto.InternalMessageInfo

func (m *ProxyUnregisterReq) GetRemotePort() []int32 {
	if m != nil {
		return m.RemotePort
	}
	return nil
}

type ProxyUnregisterResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyUnregisterResp) Reset()         { *m = ProxyUnregisterResp{} }
func (m *ProxyUnregisterResp) String() string { return proto.CompactTextString(m) }
func (*ProxyUnregisterResp) ProtoMessage()    {}
func (*ProxyUnregisterResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{4}
}

func (m *ProxyUnregisterResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyUnregisterResp.Unmarshal(m, b)
}
func (m *ProxyUnregisterResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyUnregisterResp.Marshal(b, m, deterministic)
}
func (m *ProxyUnregisterResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyUnregisterResp.Merge(m, src)
}
func (m *ProxyUnregisterResp) XXX_Size() int {
	return xxx_messageInfo_ProxyUnregisterResp.Size(m)
}
func (m *ProxyUnregisterResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyUnregisterResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyUnregisterResp proto.InternalMessageInfo

func (m *ProxyUnregisterResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

// 映射列表
type ProxyListReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyListReq) Reset()         { *m = ProxyListReq{} }
func (m *ProxyListReq) String() string { return proto.CompactTextString(m) }
func (*ProxyListReq) ProtoMessage()    {}
func (*ProxyListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{5}
}

func (m *ProxyListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyListReq.Unmarshal(m, b)
}
func (m *ProxyListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyListReq.Marshal(b, m, deterministic)
}
func (m *ProxyListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyListReq.Merge(m, src)
}
func (m *ProxyListReq) XXX_Size() int {
	return xxx_messageInfo_ProxyListReq.Size(m)
}
func (m *ProxyListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyListReq proto.InternalMessageInfo

type ProxyListResp struct {
	Maps                 []*ProxyMapping `protobuf:"bytes,1,rep,name=maps,proto3" json:"maps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ProxyListResp) Reset()         { *m = ProxyListResp{} }
func (m *ProxyListResp) String() string { return proto.CompactTextString(m) }
func (*ProxyListResp) ProtoMessage()    {}
func (*ProxyListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{6}
}

func (m *ProxyListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyListResp.Unmarshal(m, b)
}
func (m *ProxyListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyListResp.Marshal(b, m, deterministic)
}
func (m *ProxyListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyListResp.Merge(m, src)
}
func (m *ProxyListResp) XXX_Size() int {
	return xxx_messageInfo_ProxyListResp.Size(m)
}
func (m *ProxyListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyListResp proto.InternalMessageInfo

func (m *ProxyListResp) GetMaps() []*ProxyMapping {
	if m != nil {
		return m.Maps
	}
	return nil
}

// 穿透消息
type ProxyMessageReq struct {
	ConnID               uint32   `protobuf:"varint,1,opt,name=connID,proto3" json:"connID,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyMessageReq) Reset()         { *m = ProxyMessageReq{} }
func (m *ProxyMessageReq) String() string { return proto.CompactTextString(m) }
func (*ProxyMessageReq) ProtoMessage()    {}
func (*ProxyMessageReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{7}
}

func (m *ProxyMessageReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyMessageReq.Unmarshal(m, b)
}
func (m *ProxyMessageReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyMessageReq.Marshal(b, m, deterministic)
}
func (m *ProxyMessageReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyMessageReq.Merge(m, src)
}
func (m *ProxyMessageReq) XXX_Size() int {
	return xxx_messageInfo_ProxyMessageReq.Size(m)
}
func (m *ProxyMessageReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyMessageReq.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyMessageReq proto.InternalMessageInfo

func (m *ProxyMessageReq) GetConnID() uint32 {
	if m != nil {
		return m.ConnID
	}
	return 0
}

func (m *ProxyMessageReq) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ProxyMessageResp struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyMessageResp) Reset()         { *m = ProxyMessageResp{} }
func (m *ProxyMessageResp) String() string { return proto.CompactTextString(m) }
func (*ProxyMessageResp) ProtoMessage()    {}
func (*ProxyMessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_700b50b08ed8dbaf, []int{8}
}

func (m *ProxyMessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyMessageResp.Unmarshal(m, b)
}
func (m *ProxyMessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyMessageResp.Marshal(b, m, deterministic)
}
func (m *ProxyMessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyMessageResp.Merge(m, src)
}
func (m *ProxyMessageResp) XXX_Size() int {
	return xxx_messageInfo_ProxyMessageResp.Size(m)
}
func (m *ProxyMessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyMessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyMessageResp proto.InternalMessageInfo

func (m *ProxyMessageResp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*ProxyMapping)(nil), "proxy_mapping")
	proto.RegisterType((*ProxyRegisterReq)(nil), "proxy_register_req")
	proto.RegisterType((*ProxyRegisterResp)(nil), "proxy_register_resp")
	proto.RegisterType((*ProxyUnregisterReq)(nil), "proxy_unregister_req")
	proto.RegisterType((*ProxyUnregisterResp)(nil), "proxy_unregister_resp")
	proto.RegisterType((*ProxyListReq)(nil), "proxy_list_req")
	proto.RegisterType((*ProxyListResp)(nil), "proxy_list_resp")
	proto.RegisterType((*ProxyMessageReq)(nil), "proxy_message_req")
	proto.RegisterType((*ProxyMessageResp)(nil), "proxy_message_resp")
}

func init() { proto.RegisterFile("proxy.proto", fileDescriptor_700b50b08ed8dbaf) }

var fileDescriptor_700b50b08ed8dbaf = []byte{
	// 280 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xbb, 0x4f, 0xc3, 0x30,
	0x10, 0xc6, 0x15, 0xd2, 0x56, 0xca, 0x85, 0x96, 0x62, 0x1e, 0xca, 0x82, 0x88, 0x3c, 0x40, 0x58,
	0x3a, 0x80, 0x10, 0x6c, 0x48, 0x88, 0x85, 0x0d, 0x79, 0x64, 0x89, 0x4c, 0x6a, 0x45, 0x91, 0x12,
	0xdb, 0xb5, 0x0f, 0x09, 0xfe, 0x7b, 0x94, 0x73, 0x11, 0x04, 0x32, 0x74, 0xbb, 0xfb, 0xee, 0xf1,
	0xfd, 0x7c, 0x86, 0xd4, 0x3a, 0xf3, 0xf1, 0xb9, 0xb2, 0xce, 0xa0, 0xe1, 0x1b, 0x98, 0x53, 0x5a,
	0x76, 0xd2, 0xda, 0x46, 0xd7, 0xec, 0x0c, 0xa0, 0x35, 0x95, 0x6c, 0x4b, 0x6b, 0x1c, 0x66, 0x51,
	0x1e, 0x15, 0x53, 0x91, 0x90, 0xf2, 0x62, 0x1c, 0xb2, 0x73, 0x48, 0x9d, 0xea, 0x0c, 0xaa, 0x50,
	0xdf, 0xa3, 0x3a, 0x04, 0x89, 0x1a, 0x72, 0x48, 0xd7, 0xca, 0x57, 0xae, 0xb1, 0xd8, 0x18, 0x9d,
	0xc5, 0x79, 0x54, 0x24, 0xe2, 0xb7, 0xc4, 0xef, 0x81, 0x05, 0x4b, 0xa7, 0xea, 0xc6, 0xa3, 0x72,
	0xa5, 0x53, 0x1b, 0xc6, 0x61, 0xd2, 0x49, 0xeb, 0xb3, 0x28, 0x8f, 0x8b, 0xf4, 0x7a, 0xb1, 0x1a,
	0x50, 0x09, 0xaa, 0xf1, 0x4b, 0x38, 0xfa, 0x37, 0xe9, 0x2d, 0x5b, 0x42, 0xdc, 0xf9, 0x9a, 0x58,
	0x13, 0xd1, 0x87, 0xfc, 0x0e, 0x8e, 0x43, 0xe3, 0xbb, 0x1e, 0x98, 0xfc, 0xa1, 0xef, 0xbd, 0x06,
	0xf4, 0xfc, 0x0a, 0x4e, 0x46, 0x06, 0x47, 0x3d, 0x96, 0xb0, 0x08, 0xad, 0x6d, 0xe3, 0xb1, 0xdf,
	0xce, 0x6f, 0xe1, 0x60, 0xa0, 0x78, 0xbb, 0xd3, 0xab, 0x1e, 0xe0, 0x70, 0x2b, 0x2b, 0xef, 0x65,
	0xad, 0x88, 0xf4, 0x14, 0x66, 0x95, 0xd1, 0xfa, 0xf9, 0x89, 0x2c, 0xe7, 0x62, 0x9b, 0x31, 0x06,
	0x93, 0xb5, 0x44, 0x49, 0x87, 0xdf, 0x17, 0x14, 0xf3, 0x8b, 0xef, 0x83, 0xfe, 0x2c, 0x18, 0x23,
	0x7e, 0x9c, 0xbe, 0xc6, 0x5a, 0xe1, 0xdb, 0x8c, 0x7e, 0xfe, 0xe6, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x7c, 0xa5, 0xeb, 0x35, 0x08, 0x02, 0x00, 0x00,
}
